### ISSUE TITLE
Fix the deviation of the highlight marker.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#101]
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-05-23%20at%203.44.22%20PM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@pratikmdhr do you remember this details? To adjust the offset of the highlight, we just fixed the problem with the hovering area for mouse.

**Comment by pratikmdhr** [comment]
@dadiorchen does this also happen on map core? i remember we had issue with the number in the icon: https://github.com/Greenstand/treetracker-web-map-core/issues/82#issuecomment-1035139245. And it looked fine in the map-core, but was shifted in the map-client..

If the issue occurs in map-core too, we can just shift the icons down. But if it only happens in map-client, then we need to check it in more detail.. I will look into this

**Comment by pratikmdhr** [comment]
@dadiorchen turns out it was happening in the map core too, so I adjusted the position and made the PR
