### ISSUE TITLE
Previous (big) circles not disposed properly upon zoom in

### ISSUE THREAD

**Issue by michaltrunek** [Greenstand/treetracker-web-map-core#11]
Upon zooming in (fast) or clicking on regions, the previous big circles with number of trees in regions are disappearing very slowly most of the time. The big circle is zoomed in and is covering big part of the screen and at the same time we are already loading another/detailed regions with tree numbers. This doesn't look nice for a user. We should dispose/dismiss the previous circle more effectively.

**Details:**
Mobile and Desktop devices

https://user-images.githubusercontent.com/4280850/123460703-50d1fc80-d5e8-11eb-927b-c8aa45fd1011.mov

**Comment by keyy123** [comment]
Should we mark this issue as closed/moved/transferred? 🤔

**Comment by dadiorchen** [comment]
Yes, we will migrate to beta, so let's close this
