### ISSUE TITLE
Core: problem with the next tree button

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#121]
Seems we are missing some style? the layout for the button is incorrect, and also, we need some feedback for the button: highlight the button when the mouse hovering, and change the mouse pointer to `clickable pointer`

![Image](https://user-images.githubusercontent.com/5744708/192977619-c3df7c75-9446-4ebf-8437-1b10d65a688c.png)

**Comment by dadiorchen** [comment]
@RubenSmn can you look at this? I'm not sure what's the problem, but when I download the core and run on my computer, the button's layout seems incorrect

**Comment by dadiorchen** [comment]
Also please add some feedback on the button

**Comment by RubenSmn** [comment]
Will have a look!

**Comment by RubenSmn** [comment]
I will add some feedback for the button.

The position of the buttons seems to be working:
![image](https://user-images.githubusercontent.com/31519867/192980214-8099849a-02bc-4366-b875-63f1069b0793.png)

**Comment by dadiorchen** [comment]
I think maybe it's because the webpack bundle, if I install the core on web map client, the layout is bad, and the button doesn't work, can not click to jump to next tree, there are some error throwing from main.js (the core bundle) saying: failed to read `style` from undefined

**Comment by dadiorchen** [comment]
@RubenSmn here is how to install the core locally: https://github.com/Greenstand/treetracker-web-map-core#how-to-debug-the-core-on-the-client-side

**Comment by RubenSmn** [comment]
Ah that is possible, for the customizable web map I need a ColorPicker but it was not compatible with NextJS giving the same error. I do not know what or how, but it has something to do with the babel config

**Comment by dadiorchen** [comment]
By the approach above, you can install your version of core into web map client

**Comment by RubenSmn** [comment]
Btw, I am changing the buttons to only be an SVG on the arrows, the rest will just be an element. So we can easily change the buttons appearance, for example for feedback.

**Comment by RubenSmn** [comment]
> I think maybe it's because the webpack bundle, if I install the core on web map client, the layout is bad, and the button doesn't work, can not click to jump to next tree, there are some error throwing from main.js (the core bundle) saying: failed to read `style` from undefined

This was due to a element being undefined

**Comment by dadiorchen** [comment]
@RubenSmn this is working perfectly!
