### ISSUE TITLE
Update `lng` to `lon` for consistancy

### ISSUE THREAD

**Issue by RubenSmn** [Greenstand/treetracker-web-map-core#127]
# Description
Currently we are using both `lon` and `lng` in our code.
For consistancy we should update `lng` to `lon` since it is the most commonly used.

Reason: in the Web Map all the entities (trees) are using `lon` for coordinates.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by muhon9** [comment]
I will work on the issue
