### ISSUE TITLE
Add `npm test` into the CI and make sure every Jest test past

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#129]
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by keyy123** [comment]
Can I try this ticket? 🙂

**Comment by dadiorchen** [comment]
Definitely, thank you!

**Comment by dadiorchen** [comment]
Let me know if you need any resource for this

**Comment by RubenSmn** [comment]
Resolved by #145
