### ISSUE TITLE
Open event `on` and `off` API

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#158]
Currently, we offer the `map.on('event_name')` to register a listener, now we need to open the `off` `once` API to unregister and one-time-listener, check the document here:

https://nodejs.org/api/events.html#emitteronceeventname-listener
https://nodejs.org/api/events.html#emitteroneventname-listener

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by XLPeng57** [comment]
@dadiorchen Hi, I'm new to web-map-core. Is this still an issue? If yes, could you assign it to me? I'd like to work on this! If not, are there any issues you'd recommend for me to work on?

**Comment by dadiorchen** [comment]
@XLPeng57 yes, please take this issue, I'm thinking about how to test it when you finished, any idea?
