### ISSUE TITLE
Set up project tools like husky, eslint, prettier

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#2]
Need to:
* Install eslint and rules (.eslintrc)
* Install prettier and rules
* Install husky for: 
  * auto check and fix eslint error/warning when commiting.
  * auto format code when committing.
* add simple guide into `readme` explaining how to use these commands.

This project should be the same as this repo:  https://github.com/Greenstand/treetracker-web-map-client
So please refer to it.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by QuaidBartolomei** [comment]
I will work on this. @dadiorchen I want to add [sort-package-json](https://www.npmjs.com/package/sort-package-json) as well. It works with lint-staged to sort the package any time it is changed. This makes sure that the package.json contents are always in a consistent order.
