### ISSUE TITLE
Release web map core as a NPM module

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#23]
We can not use/import the leaflet css when we installing the core to other project, like the treetracker-web-map-client next.js will throw error:

![image](https://user-images.githubusercontent.com/5744708/141260157-0b939e57-c915-450c-af2b-b09c6ccaa12d.png)

the reason: 
https://nextjs.org/docs/messages/css-npm

Seems because we didn't import the bin/dist of the bundle, we directly import the `src` file in client, please figure out the correct way to install this package/lib to other clients.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
https://github.com/Greenstand/treetracker-web-map-core/blob/906211873877bff90a956e7040db59ddce0046c7/src/Map.js#L8-L11

**Comment by dadiorchen** [comment]
For a tempororially work around, open the /node_modules/treetracer-web-map-core/src/Map.js and delete the line: 
```
 import 'leaflet/dist/leaflet.css'; 
```

**Comment by QuaidBartolomei** [comment]
I am working on a solution to this
