### ISSUE TITLE
Migrate the `nearest` feature from the web-map-client to core

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#30]
we need to migrate the code below to the core:
https://github.com/Greenstand/treetracker-web-map-client/blob/9257c09f6d56d8a041b28e26f7eb52dbde7f33bf/src/components/App.js#L321-L340

because it is more about a pure map operation.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by pratikmdhr** [comment]
i'll work on this

**Comment by dadiorchen** [comment]
Thanks @pratikmdhr you helped a lot!

**Comment by pratikmdhr** [comment]
glad to help!

**Comment by dadiorchen** [comment]
@pratikmdhr what's the situation of this issue?
