### ISSUE TITLE
Publish the web map core to npm cloud

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#33]
So we can install this repo by `npm install @greenstand/treetracker-web-map-core`

Please ask me for the greenstand official npm account.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by keyy123** [comment]
@dadiorchen, is this ticket still open? I would like to try it.

**Comment by dadiorchen** [comment]
This is finished
