### ISSUE TITLE
Install husky and commit message plugin

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#34]
So we can check the commit message following the rule like: `feat: some feature`

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@VWRoli you ever installed husky before right? can you help to install it here? I met some problem to install, maybe Chinese wall related...

**Comment by VWRoli** [comment]
> @VWRoli you ever installed husky before right? can you help to install it here? I met some problem to install, maybe Chinese wall related...

Sure, I will take a look at it tomorrow.
