### ISSUE TITLE
Can not update the version in package.json

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#40]
Now in the github action, the `main.yaml` (please run it with branch `main`) will make a release and create correct tag in the repo, but the problem is that the `package.json` 's version can not be updated automatically. 

https://github.com/Greenstand/treetracker-web-map-core/blob/ab4d306e69747d9c85d555038c05ebefe35aac4d/package.json#L1-L6

So the version tag doesn't match the npm package.json version.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by diegovanelli** [comment]
I think this problem was solved in version: 1.0.4:
https://github.com/Greenstand/treetracker-web-map-core/commit/da143c13ef23d3fb883508c676cda2563a6f83b7

Probably when was altered the file ".releaserc", added line "npmPublish": false

**Comment by emmanue** [comment]
Indeed this issue was fixed with this commit https://github.com/Greenstand/treetracker-web-map-core/commit/88c07c894d873409abf7c495551b9426005a4fa0 Thanks @diegovanelli  and @yi-xuan-97  for your contributions.
