### ISSUE TITLE
Automatically pack the core with webpack

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#41]
Currently, the way to release a new version is:
1. run `npm run pre-publish` to build the bundle with webpack.
2. commit the code
3. run the github action to release the tag

It's inconvenient and easy to make mistakes (forgot to run the command), so we need to pack the code automatically every time we release a version.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by Siddhant-K-code** [comment]
It is already resolved, i guess!
