### ISSUE TITLE
Be able to highlight the tree icon after clicking (jump to single tree page)

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#47]
https://user-images.githubusercontent.com/5744708/140253671-ca801dc5-c57e-481a-b24a-9e04a71c6b68.mov

Just like what we do on https://map.treetracker.org

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-client#treetracker-web) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
Another reminder, we have now created a new suit of icon, the green one. The color of the icon could be set by this: 

```
NEXT_PUBLIC_TILE_SERVER_URL=https://{s}.treetracker.org/tiles/new/
NEXT_PUBLIC_TILE_SERVER_URL=https://{s}.treetracker.org/tiles/
```

**Comment by pratikmdhr** [comment]
got it.. thanks!

**Comment by keyy123** [comment]
Please, mark this issue as closed. 🙂
