### ISSUE TITLE
A guide of how to publish the core to npm

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#55]
By executing github action.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by github4maninder** [comment]
Hi, I would like to work on this Issue.

**Comment by keyy123** [comment]
@dadiorchen, Is this a guide on how to publish the API (web-map-core) to npmjs.com as a private repo using github actions?

**Comment by dadiorchen** [comment]
Please ignore this
