### ISSUE TITLE
A new option to switch between different icon suits.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#61]
We need to use an option to set the icon style (switch between icons suits), it could be like: 
```
new Map({
  iconSuite: 'old' | 'green',
}
```

In the near future, we at least have three suites of icon:
1. the old orange icon for current online version. 
2. The green icon we already support now.
3. A eclipse green version for destop (big screen side)

In the future, it's possible we are going to design a new icon for our VIP partner.

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by pratikmdhr** [comment]
i'll work on this

**Comment by dadiorchen** [comment]
@pratikmdhr I think this consideration below is relevant with this issue:

https://github.com/Greenstand/treetracker-web-map-core/blob/2bde9cb6ce0f3c668db2a29260c292bc014ca13f/src/Map.js#L36-L39

I'm thinking that we shouldn't change the icon by setting the tile URL directly, we should modify the URL on the fly, I mean by appending the `/new/` into the URL according to the option.

what do you think?

**Comment by pratikmdhr** [comment]
yes i agree, i was planning on dynamically changing the URL too..
