### ISSUE TITLE
Support the new icon spec.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#71]
Now we defined a new spec for the icon URL/route rule:

Use `icon=o' query pamaeter rather than the path `/new/` to choose the icon suite.

The spec details is here: https://greenstand.gitbook.io/wallet-web-app/tile-server-specification

So we need to modify the core to follow the new rule.

Here are some links for the design elements: 

https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=5336%3A19844

Tree icon:
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=6131%3A21214

Highlighted tree:
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=6133%3A21308

Selected tree:
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=6133%3A26944

Small size:
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=5336%3A19844

Basically, the big and small icons are just different in size, the shape is the same. The way I'm doing in tile server is: export the element from Figma, choose 3x size png, so the icon would be clear when I display it. I just need to shrink the image to get the correct icon: 
for desktop: 
transform: scale(0.33);

for mobile:
transform: scale(0.27);

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@pratikmdhr can you take a look at this?

**Comment by dadiorchen** [comment]
https://dev-k8s.treetracker.org/tiles/1/1/1.png?icon=ptk-s
https://dev-k8s.treetracker.org/tiles/1/1/1.png?icon=ptk-b

And @pratikmdhr I observed some wired version switching problem on the tile, just as we saw before, I think there are some bug on the tile, sorry about the chaos.

**Comment by pratikmdhr** [comment]
Sure I'll look into this
