### ISSUE TITLE
Move the number on the icon downward a bit

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#82]
![image](https://user-images.githubusercontent.com/5744708/153353391-8eb59b4d-4f76-4e3a-a1b3-cf9364a2879c.png)

Otherwise move the mouse over the icon, the highlighted icon has some difference with the original icon
https://dadior.s3.ap-northeast-1.amazonaws.com/Screen%20Recording%202022-02-10%20at%202.51.33%20PM.mp4

---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by dadiorchen** [comment]
@pratikmdhr can you take this? I think you just need to change a little bit on the highlighted icon svg?

**Comment by pratikmdhr** [comment]
@dadiorchen yes, i will fix this

**Comment by keyy123** [comment]
Please, mark this issue as closed 🙂.
