### ISSUE TITLE
Bad arrow icon style

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-web-map-core#98]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/5744708/169632859-48bcbafa-0c54-4b72-af43-955a2d852295.png">

Please check our Figma design for correct style spec :
https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=3765%3A12671
The position of the icon is fine, just correct the arrow style.
---

Some hints:

- Please read our [readme](https://github.com/Greenstand/treetracker-web-map-core#treetracker-web-map-core) for more information/guide/tutorial.
- Here is [an engineering book](https://greenstand.gitbook.io/engineering/) in Greenstand.
- To know more about our organization, visit our [website](https://greenstand.org).
- If you want to join the slack community (some resources need the community member's permission), please leave your email address.

**Comment by muhon9** [comment]
@dadiorchen I want to work on these issue

**Comment by dadiorchen** [comment]
Hi, muhon, this one has been solved by Ruben in the PR above, so we will close it, could you pick another one?

**Comment by muhon9** [comment]
Oh great. I will try to find some other issue where i can contribute
